# This source code is licensed under the license found in the
# LICENSE file in the root directory of this source tree.

batch_size: 64
compile: true
detect_divergence: true
devices: "auto"
eps: 1e-12
n_accum_steps: 1
n_epochs: 100
n_frames: 3
n_pixels: 64
n_workers: 4
patience: -1
precision: "32-true"
seed: 0
watched_metric_strategy: "max"
watched_metric: "E_3D"